### ISSUE TITLE
Epic: Integration Tests

### ISSUE THREAD

**Issue by cdhoffmann** [adobe/aepsdk-target-ios#17]
- [x] Prefetch Integration tests
- [x] Preview Integration tests
- [x] Batch Integration tests
- [ ] Notification integration tests
